openapi: 3.0.3
info:
  title: Todo App API
  description: >-
    RESTful API for a simple todo app written in Haskell using scotty and
    postgresql-simple. The source code can be found
    [here](https://github.com/xddq/haskell-simple-todo)
  license:
    name: BSD-3-Clause
    url: https://opensource.org/license/BSD-3-clause/
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: todo
    description: Everything about your todos
paths:
  /todos:
    get:
      tags:
        - todo
      summary: List todos
      description: Lists all todos
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
               schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
       tags:
         - todo
       summary: Create todo
       description: Creates a single todo
       requestBody:
         $ref: '#/components/requestBodies/CreateTodo'
       responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '400':
            description: Invalid Input
          '500':
            description: server error
  /todos/{todoId}:
    get:
      tags:
        - todo
      summary: Get todo by ID
      description: Returns a single todo
      parameters:
        - name: todoId
          in: path
          description: ID of todo to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
         '200':
           description: successful operation
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Todo'
         '400':
           description: invalid input
         '404':
           description: Not found
    patch:
       tags:
         - todo
       summary: Update todo by ID
       description: Updates a single todo
       parameters:
         - name: todoId
           in: path
           description: ID of todo to update
           required: true
           schema:
             type: integer
             format: int64
       requestBody:
         $ref: '#/components/requestBodies/UpdateTodo'
       responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '400':
            description: Invalid input
          '404':
            description: Not found
    delete:
       tags:
         - todo
       summary: Delete todo by ID
       description: Deletes a single todo
       parameters:
         - name: todoId
           in: path
           description: ID of todo to delete
           required: true
           schema:
             type: integer
             format: int64
       responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: string
          '400':
            description: Invalid input
          '404':
            description: Not found

components:
  schemas:
    Todo:
      required:
        - text
        - id
        - done
      properties:
        id:
          type: integer
          format: int64
          example: 3
        text:
          type: string
          example: review pr
        done:
          type: boolean
          example: false
  requestBodies:
    CreateTodo:
      description: Todo that will be created
      content:
        application/json:
          schema:
            required:
              - text
              - done
            properties:
              text:
                type: string
                example: review pr
              done:
                type: boolean
                example: false
    UpdateTodo:
      description: Todo that will be updated
      content:
        application/json:
          schema:
            required:
              - id
              - done
              - text
            properties:
              id:
                type: integer
                format: int64
                example: 2
              text:
                type: string
                example: review pr
              done:
                type: boolean
                example: false
